USE [NewLb]
GO

/****** Object:  Table [dbo].[PLAYER]    Script Date: 26.10.2020 22:18:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [TUser].[PLAYER1](
	[PLAYER_ID] [smallint] IDENTITY(1,1) NOT NULL,
	[LASTNAME] [varchar](20) NOT NULL,
	[NAME] [varchar](20) NOT NULL,
	[PATRONYMIC] [varchar](20) NOT NULL,
	[BIRTHDAY] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PLAYER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


