USE [NewLb]
GO

/****** Object:  Table [dbo].[SEASON]    Script Date: 26.10.2020 22:18:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Tuser].[SEASON1](
	[SEASON_ID] [smallint] NOT NULL,
	[SEASON_YEAR] [smallint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SEASON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


