	--не работает нигде!!

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE


BEGIN TRANSACTION

UPDATE GAME_REPORT SET SCORE_PLAYER = 100 WHERE PLAYER_ID = 1 and GAME_ID = 1
SELECT * FROM GAME_REPORT where PLAYER_ID = 1 and GAME_ID = 1
--
COMMIT

SELECT * FROM GAME_REPORT where PLAYER_ID = 1 and GAME_ID = 1