--2.1-Потерянные изменения
-- случается с READ COMMITTED и READ UNCOMMITTED

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE


BEGIN TRAN

Declare @p int
Set @p=(select SCORE_PLAYER   FROM GAME_REPORT
WHERE game_id = 2 AND player_id = 3)
select @p

WAITFOR DELAY '00:00:10'

UPDATE GAME_REPORT
SET SCORE_PLAYER = @p+ 10
WHERE game_id =  2 AND player_id = 3
COMMIT

SELECT * FROM GAME_REPORT
WHERE game_id = 2 AND player_id = 3