--3.1-Неповторяющееся чтение
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED--видна проблема
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ--нет проблемы
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE


BEGIN TRAN

Select *  FROM GAME_REPORT
WHERE game_id = 2 AND player_id = 3

--

SELECT * FROM GAME_REPORT
WHERE game_id = 2 AND player_id = 3

COMMIT
