--2.2-Неповторяющееся чтение
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED--видна проблема
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ--нет проблемы
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
 


SELECT * FROM GAME_REPORT
WHERE game_id = 2 AND player_id = 3

BEGIN TRAN

UPDATE GAME_REPORT
SET SCORE_PLAYER = SCORE_PLAYER+ 20
WHERE game_id = 2 AND player_id = 3

COMMIT

SELECT * FROM GAME_REPORT
WHERE game_id = 2 AND player_id = 3
