--4.2-фантомы
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ --видна проблема
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- нет проблемы
SET IDENTITY_INSERT dbo.PLAYER ON; 
--смотрим список Вань
SELECT * FROM PLAYER 
WHERE name = 'иван'

BEGIN TRAN

--добавляем Ваню в таблицу

INSERT INTO [dbo].[PLAYER] ([player_id],[LASTNAME],[NAME],[PATRONYMIC],[BIRTHDAY])VALUES(1010,'Петров','Иван','Джиннович','2004-05-07')

COMMIT

--смотрим список Вань
SELECT * FROM PLAYER 
WHERE name = 'иван'
